const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let contacts=JSON.parse(localStorage.getItem('discadora_contacts')||'[]');
let history=JSON.parse(localStorage.getItem('discadora_history')||'[]');
let idx=Number(localStorage.getItem('discadora_idx')||0);
let calls=Number(localStorage.getItem('discadora_calls')||0);
let script=localStorage.getItem('discadora_script')||$('#script').value;
const pageNames={dashboard:'Visão geral',contatos:'Contatos',campanha:'Campanha',config:'Configurações'};
function save(){localStorage.setItem('discadora_contacts',JSON.stringify(contacts));localStorage.setItem('discadora_history',JSON.stringify(history));localStorage.setItem('discadora_idx',String(idx));localStorage.setItem('discadora_calls',String(calls));localStorage.setItem('discadora_script',script)}
function normPhone(v){let d=String(v||'').replace(/\D/g,'');if(d.startsWith('55'))return '+'+d;if(d.length===10||d.length===11)return '+55'+d;return d?'+'+d:''}
function current(){if(!contacts.length)return null;if(contacts[idx]&&!['interested','optout','done'].includes(contacts[idx].status)&&contacts[idx].status!=='calling')return contacts[idx];const n=contacts.findIndex(c=>!['interested','optout','done'].includes(c.status)&&c.status!=='calling');if(n>=0){idx=n;return contacts[n]}return null}
function label(s){return({interested:'Interessado',optout:'Não ligar',callback:'Retornar',noanswer:'Não atendeu',calling:'Ligando',done:'Concluído'}[s]||'Pendente')}
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function render(){const c=current();$('#total').textContent=contacts.length;$('#calls').textContent=calls;$('#interested').textContent=contacts.filter(x=>x.status==='interested').length;$('#optout').textContent=contacts.filter(x=>x.status==='optout').length;$('#scriptPreview').textContent=script;$('#showwa').checked=localStorage.getItem('discadora_showwa')!=='0';if(!c){$('#name').textContent='Fila concluída';$('#phone').textContent=contacts.length?'Não há contatos pendentes.':'Importe uma lista CSV para começar.';$('#company').textContent='Tudo em dia';$('#notes').textContent=contacts.length?'Revise os resultados ou importe uma nova lista.':'Nome, telefone e empresa são reconhecidos automaticamente.';$('#avatar').textContent='✓';$('#badge').textContent='Concluído';$('#call').disabled=true;$('#wa').disabled=true}else{$('#name').textContent=c.name||'Sem nome';$('#phone').textContent=c.phone||'';$('#company').textContent=c.company||'Contato';$('#notes').textContent=c.notes||'Pronto para contato';$('#avatar').textContent=(c.name||'?').trim().slice(0,1).toUpperCase();$('#badge').textContent=label(c.status);$('#call').disabled=false;$('#wa').disabled=false}renderTable();renderRecent();save()}
function renderTable(){const q=$('#search').value.toLowerCase();const arr=contacts.filter(c=>Object.values(c).join(' ').toLowerCase().includes(q));$('#count').textContent=`${arr.length} contato${arr.length===1?'':'s'}`;$('#tbody').innerHTML=arr.length?arr.map(c=>{const i=contacts.indexOf(c);return `<tr><td><b>${esc(c.name||'Sem nome')}</b></td><td>${esc(c.phone)}</td><td>${esc(c.company||'—')}</td><td>${label(c.status)}</td><td><button class="link" data-open="${i}">Abrir</button></td></tr>`}).join(''):'<tr><td colspan="5" class="empty">Nenhum contato encontrado.</td></tr>';$$('[data-open]').forEach(b=>b.onclick=()=>{idx=Number(b.dataset.open);render();show('dashboard')})}
function renderRecent(){$('#recent').innerHTML=history.slice(-8).reverse().map(h=>`<div class="recent-item"><b>${esc(h.name||'Contato')}</b><span>${esc(h.result)} · ${new Date(h.time).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})}</span></div>`).join('')||'<div class="empty">Nenhuma atividade registrada.</div>'}
function show(view){$$('.nav-item').forEach(b=>b.onclick=()=>show(b.dataset.view));$('#goContacts').onclick=()=>show('contatos');$('#addSingle').onclick=()=>{const d=$('#singlePhone').value.replace(/\D/g,'');if(d.length!==10&&d.length!==11){alert('Digite DDD + número. Ex.: 11999998888');return}addNumbers([d]);$('#singlePhone').value=''};$('#singlePhone').addEventListener('keydown',e=>{if(e.key==='Enter')$('#addSingle').click()});$('#phoneList').oninput=e=>{const n=listValues(e.target.value).length;$('#listCount').textContent=Math.min(n,10000)+' números detectados · limite 10.000'};$('#addList').onclick=()=>{const v=listValues($('#phoneList').value);if(!v.length){alert('Cole a lista de números primeiro.');return}if(v.length>10000){alert('A lista ultrapassa o limite de 10.000 números.');return}addNumbers(v);$('#phoneList').value='';$('#listCount').textContent='0 números detectados · limite 10.000'};$('#search').oninput=renderTable;('#call').onclick=call;$('#skip').onclick=next;$('#wa').onclick=()=>{const c=current();if(c)window.open(`https://wa.me/${normPhone(c.phone).replace('+','')}?text=${encodeURIComponent(`Olá, ${c.name||''}! Gostaria de falar sobre a oferta que apresentamos por telefone.`)}`,'_blank','noopener')};$$('[data-result]').forEach(b=>b.onclick=()=>result(b.dataset.result));$('#save').onclick=()=>{script=$('#script').value.trim();save();render();alert('Roteiro salvo com sucesso.')};$('#clear').onclick=()=>{history=[];save();render()};$('#showwa').onchange=e=>{localStorage.setItem('discadora_showwa',e.target.checked?'1':'0');render()};
fetch('/api/status').then(r=>r.json()).then(x=>{$('#provider').textContent=x.configured?'Telefonia conectada':'Modo demonstração';$('#provider').previousElementSibling.style.background=x.configured?'#39c779':'#e9a62a'}).catch(()=>{$('#provider').textContent='Modo local'});
$('#script').value=script;render();
