const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let contacts=JSON.parse(localStorage.getItem('discadora_contacts')||'[]');
let history=JSON.parse(localStorage.getItem('discadora_history')||'[]');
let idx=Number(localStorage.getItem('discadora_idx')||0);
let calls=Number(localStorage.getItem('discadora_calls')||0);
let script=localStorage.getItem('discadora_script')||$('#script').value;
const pageNames={dashboard:'Visão geral',contatos:'Contatos',campanha:'Campanha',config:'Configurações'};
function save(){localStorage.setItem('discadora_contacts',JSON.stringify(contacts));localStorage.setItem('discadora_history',JSON.stringify(history));localStorage.setItem('discadora_idx',String(idx));localStorage.setItem('discadora_calls',String(calls));localStorage.setItem('discadora_script',script)}
function normPhone(v){let d=String(v||'').replace(/\D/g,'');if(d.startsWith('55'))return '+'+d;if(d.length===10||d.length===11)return '+55'+d;return ''}
function validDigits(v){const d=String(v||'').replace(/\D/g,'');return d.length===10||d.length===11?d:''}
function current(){if(!contacts.length)return null;if(idx<0||idx>=contacts.length)idx=0;if(contacts[idx]&&!['interested','optout','done','calling'].includes(contacts[idx].status))return contacts[idx];const n=contacts.findIndex(c=>!['interested','optout','done','calling'].includes(c.status));if(n>=0){idx=n;return contacts[n]}return null}
function label(s){return({interested:'Interessado',optout:'Não ligar',callback:'Retornar',noanswer:'Não atendeu',calling:'Ligando',done:'Concluído'}[s]||'Pendente')}
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function listValues(text){return String(text||'').split(/[\n,;\t ]+/).map(validDigits).filter(Boolean)}
function addNumbers(values){const incoming=[];for(const value of values){const d=validDigits(value);if(d)incoming.push(normPhone(d))}const unique=[...new Set(incoming)].slice(0,10000);const existing=new Set(contacts.map(c=>normPhone(c.phone)));const fresh=unique.filter(p=>!existing.has(p));fresh.forEach(phone=>contacts.push({name:'',phone,company:'',notes:'',status:''}));idx=contacts.findIndex(c=>!['interested','optout','done','calling'].includes(c.status));history.push({name:'Lista',result:fresh.length+' contato(s) adicionado(s)',time:new Date().toISOString()});save();render();alert(fresh.length?fresh.length+' número(s) adicionado(s) com sucesso.':'Nenhum número novo foi adicionado (duplicados ou já cadastrados).')}
function render(){const c=current();$('#total').textContent=contacts.length;$('#calls').textContent=calls;$('#interested').textContent=contacts.filter(x=>x.status==='interested').length;$('#optout').textContent=contacts.filter(x=>x.status==='optout').length;$('#scriptPreview').textContent=script;$('#showwa').checked=localStorage.getItem('discadora_showwa')!=='0';if(!c){$('#name').textContent='Fila concluída';$('#phone').textContent=contacts.length?'Não há contatos pendentes.':'Adicione um número para começar.';$('#company').textContent='Tudo em dia';$('#notes').textContent=contacts.length?'Revise os resultados ou adicione novos números.':'Digite um número ou cole uma lista na seção Contatos.';$('#avatar').textContent='✓';$('#badge').textContent='Concluído';$('#call').disabled=true;$('#wa').disabled=true}else{$('#name').textContent=c.name||'Sem nome';$('#phone').textContent=c.phone||'';$('#company').textContent=c.company||'Contato';$('#notes').textContent=c.notes||'Pronto para contato';$('#avatar').textContent=(c.name||c.phone||'?').trim().slice(-1).toUpperCase();$('#badge').textContent=label(c.status);$('#call').disabled=false;$('#wa').disabled=false}renderTable();renderRecent();save()}
function renderTable(){const q=($('#search').value||'').toLowerCase().trim();const arr=contacts.map((c,i)=>({c,i})).filter(x=>Object.values(x.c).join(' ').toLowerCase().includes(q));$('#count').textContent=arr.length+' contato'+(arr.length===1?'':'s');$('#tbody').innerHTML=arr.length?arr.map(({c,i})=>'<tr><td><b>'+esc(c.name||'Sem nome')+'</b></td><td>'+esc(c.phone)+'</td><td>'+label(c.status)+'</td><td><button class="link" data-open="'+i+'">Abrir</button></td></tr>').join(''):'<tr><td colspan="4" class="empty">Nenhum contato encontrado.</td></tr>';$$('[data-open]').forEach(b=>b.onclick=()=>{idx=Number(b.dataset.open);save();render();show('dashboard')})}
function renderRecent(){$('#recent').innerHTML=history.slice(-8).reverse().map(h=>'<div class="recent-item"><b>'+esc(h.name||'Contato')+'</b><span>'+esc(h.result)+' · '+new Date(h.time).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})+'</span></div>').join('')||'<div class="empty">Nenhuma atividade registrada.</div>'}
function show(view){$$('.view').forEach(v=>v.classList.toggle('active',v.id===view));$$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===view));$('#pageTitle').textContent=pageNames[view]||'Visão geral'}
async function call(){const c=current();if(!c)return;$('#call').disabled=true;c.status='calling';render();calls++;save();try{const r=await fetch('/api/call',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({to:normPhone(c.phone),script})});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||'Falha ao iniciar a ligação.');history.push({name:c.name||c.phone,result:'Ligação iniciada',time:new Date().toISOString()});alert('Ligação iniciada com sucesso.')}catch(e){c.status='';calls=Math.max(0,calls-1);history.push({name:c.name||c.phone,result:'Erro: '+e.message,time:new Date().toISOString()});alert(e.message)}save();render()}
function next(){const c=current();if(c)c.status='done';const n=contacts.findIndex(x=>!['interested','optout','done','calling'].includes(x.status));idx=n>=0?n:0;save();render()}
function result(status){const c=current();if(!c)return;c.status=status;history.push({name:c.name||c.phone,result:label(status),time:new Date().toISOString()});if($('#auto').checked){const n=contacts.findIndex(x=>!['interested','optout','done','calling'].includes(x.status));idx=n>=0?n:0}save();render()}
function bind(){$$('.nav-item').forEach(b=>b.onclick=()=>show(b.dataset.view));$('#goContacts').onclick=()=>show('contatos');$('#addSingle').onclick=()=>{const d=validDigits($('#singlePhone').value);if(!d){alert('Digite DDD + número. Ex.: 11999998888');return}addNumbers([d]);$('#singlePhone').value=''};$('#singlePhone').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();$('#addSingle').click()}});$('#phoneList').addEventListener('input',e=>{const n=listValues(e.target.value).length;$('#listCount').textContent=Math.min(n,10000)+' números detectados · limite 10.000'});$('#addList').onclick=()=>{const v=listValues($('#phoneList').value);if(!v.length){alert('Cole a lista de números primeiro.');return}if(v.length>10000){alert('A lista ultrapassa o limite de 10.000 números.');return}addNumbers(v);$('#phoneList').value='';$('#listCount').textContent='0 números detectados · limite 10.000'};$('#search').addEventListener('input',renderTable);$('#call').onclick=call;$('#skip').onclick=next;$('#wa').onclick=()=>{const c=current();if(c)window.open('https://wa.me/'+normPhone(c.phone).replace('+','')+'?text='+encodeURIComponent('Olá! Demonstrei interesse na oferta apresentada por telefone e gostaria de falar com um especialista.'),'_blank','noopener')};$$('[data-result]').forEach(b=>b.onclick=()=>result(b.dataset.result));$('#save').onclick=()=>{script=$('#script').value.trim();save();render();alert('Roteiro salvo com sucesso.')};$('#clear').onclick=()=>{history=[];save();render()};$('#showwa').onchange=e=>{localStorage.setItem('discadora_showwa',e.target.checked?'1':'0');render()}}
document.addEventListener('DOMContentLoaded',()=>{bind();$('#script').value=script;fetch('/api/status').then(r=>r.json()).then(x=>{$('#provider').textContent=x.configured?'Telefonia conectada':'Modo demonstração';$('#provider').previousElementSibling.style.background=x.configured?'#39c779':'#e9a62a'}).catch(()=>{$('#provider').textContent='Modo local'});render()});